" Enable mouse for normal mode
set mouse=n


filetype on
filetype plugin indent on
set history=700
set cmdheight=2

set number

syntax on 
set autoread
set showmode
set ignorecase
set smartcase
set smartindent


set tabstop=2
set smarttab


" center view on the search result
noremap n nzz
noremap N Nzz

"Rainbow Brackets
let g:rainbow_active = 1
