" Enable mouse for normal mode
set mouse=n


filetype on
filetype indent on
set history=700
set cmdheight=2

set number

syntax on 
set autoread
set showmode
set ignorecase
set smartcase
set smartindent

set tabstop=3


" center view on the search result
noremap n nzz
noremap N Nzz

inoremap <Up> <C-O>gk
inoremap <Down> <C-O>gj